/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: pot4tochip (https://sketchfab.com/andyvargas)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bicycle-467c6873188044ee85066fa3cea957f5
title: Bicycle ^^
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group scale={0.9}>
              <mesh geometry={nodes.mesh_bike_mesh_base_bike_0.geometry} material={materials.base_bike} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
